#!/usr/bin/env Rscript
library(knitr)
knit('ASL_StructureFunction.Rnw',tangle=TRUE)
knit('ASL_StructureFunction.Rnw',tangle=FALSE)
for ( i in c(1,2,3) ) {
  system('pdflatex ASL_StructureFunction ')
  system('bibtex ASL_StructureFunction ')
}
system('rm *log *aux *blg *tex *out *bbl *spl')

